services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: postgres
      - POSTGRES_DB: subscription

    ports:
      - "5432:5432"

    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    
  volumes:
    postgres-db